'use client';
import { useState } from 'react';
import './style.css';

const api=(domain,path,params='')=>`/api/roblox/${domain}/${path}${params?`?${params}`:''}`;
const json=async(url,options)=>{const r=await fetch(url,options);const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d?.errors?.[0]?.message||`HTTP ${r.status}`);return d};
const fmtDate=v=>v?new Date(v).toLocaleString('vi-VN',{dateStyle:'long',timeStyle:'short'}):'—';
const fmtNum=n=>typeof n==='number'?new Intl.NumberFormat('vi-VN').format(n):'—';
const ago=v=>{if(!v)return'Không rõ';const days=Math.floor((Date.now()-new Date(v))/86400000);if(days<1)return'Hôm nay';if(days<30)return`${days} ngày trước`;if(days<365)return`${Math.floor(days/30)} tháng trước`;return`${Math.floor(days/365)} năm trước`};

export default function Home(){
 const[username,setUsername]=useState('');const[loading,setLoading]=useState(false);const[error,setError]=useState('');const[data,setData]=useState(null);const[tab,setTab]=useState('overview');
 async function inspect(e){e?.preventDefault();if(!username.trim())return;setLoading(true);setError('');setData(null);try{
  const found=await json(api('users','v1/usernames/users'),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({usernames:[username.trim()],excludeBannedUsers:false})});
  const u=found?.data?.[0];if(!u)throw new Error('Không tìm thấy username Roblox này.');const id=u.id;
  const results=await Promise.allSettled([
   json(api('users',`v1/users/${id}`)),json(api('thumbnails','v1/users/avatar',`userIds=${id}&size=720x720&format=Png&isCircular=false`)),
   json(api('presence','v1/presence/users'),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({userIds:[id]})}),
   json(api('groups',`v2/users/${id}/groups/roles`)),json(api('friends',`v1/users/${id}/friends`,`sortOrder=Asc&limit=100`)),json(api('friends',`v1/users/${id}/friends/count`)),json(api('friends',`v1/users/${id}/followers/count`)),json(api('friends',`v1/users/${id}/followings/count`)),json(api('badges',`v1/users/${id}/badges`,`sortOrder=Desc&limit=100`)),json(api('users',`v1/users/${id}/username-history`,`sortOrder=Desc&limit=50`)),json(api('games',`v2/users/${id}/games`,`sortOrder=Desc&limit=50`)),json(api('games',`v2/users/${id}/favorite/games`,`sortOrder=Desc&limit=50`))
  ]);const val=x=>x.status==='fulfilled'?x.value:null;
  setData({id,lookup:u,user:val(results[0]),head:val(results[1]),presence:val(results[2]),groups:val(results[3]),friends:val(results[4]),friendCount:val(results[5]),followers:val(results[6]),following:val(results[7]),badges:val(results[8]),names:val(results[9]),games:val(results[10]),favorites:val(results[11])});
 }catch(e){setError(e.message)}finally{setLoading(false)}}
 return <main><header><div className="brand"><span className="logo">R</span><div><b>RBX Insight</b><small>Roblox Account Inspector</small></div></div><a href="https://www.roblox.com" target="_blank" rel="noreferrer">Roblox ↗</a></header>
 <section className="hero"><div className="eyebrow">PUBLIC ACCOUNT ANALYTICS</div><h1>Tra cứu Roblox <span>username</span></h1><p>Xem thông tin công khai của một tài khoản Roblox trong một dashboard duy nhất.</p><form onSubmit={inspect}><input value={username} onChange={e=>setUsername(e.target.value)} placeholder="Nhập username, ví dụ: Roblox" autoCapitalize="none"/><button disabled={loading}>{loading?'Đang tra cứu…':'Tra cứu tài khoản'}</button></form>{error&&<div className="error">⚠ {error}</div>}</section>
 {!data?<section className="empty"><div className="emptyIcon">⌕</div><h2>Nhập username để bắt đầu</h2><p>Không cần mật khẩu, cookie hay đăng nhập Roblox.</p></section>:<section className="dash"><Profile data={data}/><nav className="tabs">{[['overview','Tổng quan'],['games','Game'],['badges','Badges'],['social','Bạn bè & nhóm'],['history','Lịch sử']].map(([k,v])=><button className={tab===k?'active':''} onClick={()=>setTab(k)} key={k}>{v}</button>)}</nav>{tab==='overview'&&<Overview data={data}/>} {tab==='games'&&<Games data={data}/>} {tab==='badges'&&<Badges data={data}/>} {tab==='social'&&<Social data={data}/>} {tab==='history'&&<History data={data}/>}</section>}
 <footer>Dữ liệu lấy từ các Roblox API công khai. RBX Insight không liên kết hoặc đại diện cho Roblox.</footer></main>
}
function Profile({data}){const u=data.user||data.lookup,p=data.presence?.userPresences?.[0],avatar=data.head?.data?.[0]?.imageUrl;return <div className="profile card"><div className="avatarStage"><div className="avatarWrap">{avatar?<img src={avatar} alt="Avatar"/>:<div className="avatarFallback">?</div>}<i className={p?.userPresenceType===2?'online':''}></i></div></div><div className="identity"><h2>{u?.displayName||data.lookup.displayName}</h2><div className="handle">@{u?.name||data.lookup.name} <span>#{data.id}</span></div><p>{u?.description||'Tài khoản không có mô tả công khai.'}</p><div className="chips"><span>{p?.userPresenceType===2?'● Đang chơi':p?.lastOnline?`○ Online lần cuối ${ago(p.lastOnline)}`:'○ Trạng thái ẩn'}</span><span>Tạo {fmtDate(u?.created)}</span></div></div><a className="robloxBtn" href={`https://www.roblox.com/users/${data.id}/profile`} target="_blank" rel="noreferrer">Mở profile ↗</a></div>}
function Overview({data}){const u=data.user||{},p=data.presence?.userPresences?.[0],groups=data.groups?.data||[],badges=data.badges?.data||[];const age=u.created?((Date.now()-new Date(u.created))/31557600000):0;return <><div className="stats"><Stat n={age?age.toFixed(1):'—'} l="Tuổi tài khoản (năm)"/><Stat n={fmtNum(data.friendCount?.count)} l="Bạn bè"/><Stat n={fmtNum(data.followers?.count)} l="Followers"/><Stat n={fmtNum(data.following?.count)} l="Following"/><Stat n={fmtNum(badges.length)} l="Badges đã tải"/><Stat n={fmtNum(groups.length)} l="Nhóm"/><Stat n={p?.lastLocation||'—'} l="Vị trí gần nhất"/></div><div className="grid2"><div className="card panel"><h3>Thông tin tài khoản</h3><Row a="User ID" b={data.id}/><Row a="Username" b={'@'+(u.name||data.lookup.name)}/><Row a="Display name" b={u.displayName}/><Row a="Ngày tạo" b={fmtDate(u.created)}/><Row a="Tên cũ" b={data.names?.data?.[0]?.name||'Không có dữ liệu'}/></div><div className="card panel"><h3>Trạng thái hiện tại</h3><Row a="Trạng thái" b={p?.userPresenceType===2?'Đang trong game':p?.userPresenceType===1?'Website / Studio':'Offline'}/><Row a="Game hiện tại" b={p?.lastLocation||'Không công khai'}/><Row a="Lần online cuối" b={fmtDate(p?.lastOnline)}/><Row a="Platform" b={p?.platformName||'—'}/></div></div></>}
function Games({data}){const games=data.games?.data||[],fav=data.favorites?.games||data.favorites?.data||[];return <><div className="notice">ℹ Roblox không cung cấp API công khai cho <b>tổng thời gian chơi của tài khoản trên mọi game</b>. Tab này hiển thị game đã tạo và game yêu thích công khai.</div><div className="sectionTitle"><h3>Game đã tạo ({games.length})</h3></div><div className="cards">{games.map(g=><GameCard key={g.id} g={g}/>)}</div><div className="sectionTitle"><h3>Game yêu thích ({fav.length})</h3></div><div className="cards">{fav.slice(0,50).map(g=><GameCard key={g.id||g.universeId} g={g}/>)}</div></>}
function GameCard({g}){const id=g.id||g.universeId;return <a className="game" href={`https://www.roblox.com/games/${g.rootPlaceId||g.placeId||id}`} target="_blank" rel="noreferrer"><div className="gameThumb">{g.thumbnailUrl?<img src={g.thumbnailUrl} alt=""/>:<span>ROBLOX</span>}</div><div><b>{g.name||g.displayName||'Experience'}</b><small>{g.description?.slice(0,90)||'Mở game trên Roblox'}</small><small>Visits: {fmtNum(g.placeVisits||g.visits||0)} · Updated: {fmtDate(g.updated)}</small></div></a>}
function Badges({data}){const bs=data.badges?.data||[];return <><div className="sectionTitle"><h3>Roblox Badges ({bs.length})</h3></div><div className="badgeGrid">{bs.map(b=><div className="badge" key={b.id}><div className="badgeIcon">★</div><b>{b.name}</b><small>{b.description||'Không có mô tả'}</small></div>)}</div></>}
function Social({data}){const friends=data.friends?.data||[],groups=data.groups?.data||[];return <div className="grid2"><div className="card panel"><h3>Bạn bè ({friends.length}{data.friendCount?.count>100?'+':''})</h3><div className="people">{friends.map(f=><a href={`https://www.roblox.com/users/${f.id}/profile`} target="_blank" rel="noreferrer" key={f.id}><div className="mini">{f.name[0]}</div><span>{f.displayName}<small>@{f.name}</small></span></a>)}</div></div><div className="card panel"><h3>Nhóm ({groups.length})</h3><div className="groups">{groups.map(x=><div className="group" key={x.group?.id}><b>{x.group?.name}</b><small>{x.role?.name||'Member'}</small></div>)}</div></div></div>}
function History({data}){const names=data.names?.data||[];return <div className="card panel"><h3>Lịch sử username</h3>{names.length?<div className="timeline">{names.map((x,i)=><div key={i}><i></i><b>{x.name}</b><small>{x.created?fmtDate(x.created):'Roblox không cung cấp ngày đổi tên trong endpoint này'}</small></div>)}</div>:<p>Không có lịch sử username công khai.</p>}</div>}
const Stat=({n,l})=><div className="stat card"><strong>{n||'—'}</strong><span>{l}</span></div>;const Row=({a,b})=><div className="row"><span>{a}</span><b>{b||'—'}</b></div>;
