'use client';
import { useMemo, useState } from 'react';
import './style.css';

const api=(domain,path,params='')=>`/api/roblox/${domain}/${path}${params?`?${params}`:''}`;
const json=async(url,options)=>{const r=await fetch(url,options);const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d?.errors?.[0]?.message||d?.error||`HTTP ${r.status}`);return d};
const fmtDate=v=>v?new Date(v).toLocaleString('vi-VN',{dateStyle:'long',timeStyle:'short'}):'—';
const fmtNum=n=>typeof n==='number'?new Intl.NumberFormat('vi-VN').format(n):'—';
const ago=v=>{if(!v)return'Không rõ';const days=Math.floor((Date.now()-new Date(v))/86400000);if(days<1)return'Hôm nay';if(days<30)return`${days} ngày trước`;if(days<365)return`${Math.floor(days/30)} tháng trước`;return`${Math.floor(days/365)} năm trước`};

export default function Home(){
 const[username,setUsername]=useState('');const[loading,setLoading]=useState(false);const[error,setError]=useState('');const[data,setData]=useState(null);const[tab,setTab]=useState('overview');const[query,setQuery]=useState('');
 async function inspect(e){e?.preventDefault();if(!username.trim())return;setLoading(true);setError('');setData(null);setTab('overview');try{
  const found=await json(api('users','v1/usernames/users'),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({usernames:[username.trim()],excludeBannedUsers:false})});
  const u=found?.data?.[0];if(!u)throw new Error('Không tìm thấy username Roblox này.');const id=u.id;
  const results=await Promise.allSettled([
   json(api('users',`v1/users/${id}`)),json(api('thumbnails','v1/users/avatar',`userIds=${id}&size=720x720&format=Png&isCircular=false`)),
   json(api('presence','v1/presence/users'),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({userIds:[id]})}),
   json(api('groups',`v2/users/${id}/groups/roles`)),json(api('friends',`v1/users/${id}/friends`,`sortOrder=Asc&limit=100`)),json(api('friends',`v1/users/${id}/friends/count`)),json(api('friends',`v1/users/${id}/followers/count`)),json(api('friends',`v1/users/${id}/followings/count`)),json(api('badges',`v1/users/${id}/badges`,`sortOrder=Desc&limit=100`)),json(api('users',`v1/users/${id}/username-history`,`sortOrder=Desc&limit=50`)),json(api('games',`v2/users/${id}/games`,`sortOrder=Desc&limit=50`)),json(api('games',`v2/users/${id}/favorite/games`,`sortOrder=Desc&limit=50`)),
   json(api('avatar',`v2/avatar/users/${id}/outfits`,`itemsPerPage=50&page=1&outfitType=All`)),json(api('avatar',`v2/avatar/users/${id}/avatar`)),json(api('inventory',`cloud/v2/users/${id}/inventory-items`,`maxPageSize=100`))
  ]);const val=x=>x.status==='fulfilled'?x.value:null;
  setData({id,lookup:u,user:val(results[0]),head:val(results[1]),presence:val(results[2]),groups:val(results[3]),friends:val(results[4]),friendCount:val(results[5]),followers:val(results[6]),following:val(results[7]),badges:val(results[8]),names:val(results[9]),games:val(results[10]),favorites:val(results[11]),outfits:val(results[12]),avatar:val(results[13]),inventory:val(results[14])});
 }catch(e){setError(e.message)}finally{setLoading(false)}}
 const exportData=()=>{if(!data)return;const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`rbx-insight-${data.id}.json`;a.click();URL.revokeObjectURL(a.href)};
 return <main><header><div className="brand"><span className="logo">R</span><div><b>RBX Insight <em>V3</em></b><small>Roblox Account Inspector</small></div></div><div className="headActions"><button onClick={exportData} disabled={!data}>Export JSON</button><a href="https://www.roblox.com" target="_blank" rel="noreferrer">Roblox ↗</a></div></header>
 <section className="hero"><div className="eyebrow">PUBLIC ACCOUNT ANALYTICS · V3</div><h1>Tra cứu Roblox <span>username</span></h1><p>Profile, avatar archive, outfit details, inventory, games, badges, social và lịch sử trong một dashboard.</p><form onSubmit={inspect}><input value={username} onChange={e=>setUsername(e.target.value)} placeholder="Nhập username, ví dụ: Roblox" autoCapitalize="none"/><button disabled={loading}>{loading?'Đang tải dữ liệu…':'Tra cứu tài khoản'}</button></form>{error&&<div className="error">⚠ {error}</div>}</section>
 {!data?<section className="empty"><div className="emptyIcon">⌕</div><h2>Nhập username để bắt đầu</h2><p>Không cần mật khẩu hay cookie Roblox. Inventory nâng cao cần ROBLOX_API_KEY trên server.</p></section>:<section className="dash"><Profile data={data}/><nav className="tabs">{[['overview','Tổng quan'],['avatars','Avatars'],['inventory','Inventory'],['games','Game'],['badges','Badges'],['social','Bạn bè & nhóm'],['history','Lịch sử']].map(([k,v])=><button className={tab===k?'active':''} onClick={()=>setTab(k)} key={k}>{v}</button>)}</nav>{tab==='overview'&&<Overview data={data}/>} {tab==='avatars'&&<Avatars data={data}/>} {tab==='inventory'&&<Inventory data={data} query={query} setQuery={setQuery}/>} {tab==='games'&&<Games data={data}/>} {tab==='badges'&&<Badges data={data}/>} {tab==='social'&&<Social data={data}/>} {tab==='history'&&<History data={data}/>}</section>}
 <footer>Dữ liệu lấy từ Roblox API. RBX Insight là công cụ cộng đồng, không liên kết hoặc đại diện cho Roblox.</footer></main>
}
function Profile({data}){const u=data.user||data.lookup,p=data.presence?.userPresences?.[0],avatar=data.head?.data?.[0]?.imageUrl;return <div className="profile card"><div className="avatarStage"><div className="avatarWrap">{avatar?<img src={avatar} alt="Avatar"/>:<div className="avatarFallback">?</div>}<i className={p?.userPresenceType===2?'online':''}></i></div></div><div className="identity"><h2>{u?.displayName||data.lookup.displayName}</h2><div className="handle">@{u?.name||data.lookup.name} <button className="copy" onClick={()=>navigator.clipboard?.writeText(String(data.id))}>ID {data.id} · copy</button></div><p>{u?.description||'Tài khoản không có mô tả công khai.'}</p><div className="chips"><span>{p?.userPresenceType===2?'● Đang chơi':p?.lastOnline?`○ Online lần cuối ${ago(p.lastOnline)}`:'○ Trạng thái ẩn'}</span><span>Tạo {fmtDate(u?.created)}</span></div></div><a className="robloxBtn" href={`https://www.roblox.com/users/${data.id}/profile`} target="_blank" rel="noreferrer">Mở profile ↗</a></div>}
function Overview({data}){const u=data.user||{},p=data.presence?.userPresences?.[0],groups=data.groups?.data||[],badges=data.badges?.data||[],outfits=data.outfits?.data||data.outfits?.outfits||[];const age=u.created?((Date.now()-new Date(u.created))/31557600000):0;return <><div className="stats"><Stat n={age?age.toFixed(1):'—'} l="Tuổi tài khoản (năm)"/><Stat n={fmtNum(data.friendCount?.count)} l="Bạn bè"/><Stat n={fmtNum(data.followers?.count)} l="Followers"/><Stat n={fmtNum(data.following?.count)} l="Following"/><Stat n={fmtNum(badges.length)} l="Badges tải"/><Stat n={fmtNum(groups.length)} l="Nhóm"/><Stat n={fmtNum(outfits.length)} l="Outfits"/><Stat n={p?.lastLocation||'—'} l="Game gần nhất"/></div><div className="grid2"><div className="card panel"><h3>Thông tin tài khoản</h3><Row a="User ID" b={data.id}/><Row a="Username" b={'@'+(u.name||data.lookup.name)}/><Row a="Display name" b={u.displayName}/><Row a="Ngày tạo" b={fmtDate(u.created)}/><Row a="Tên cũ gần nhất" b={data.names?.data?.[0]?.name||'Không có dữ liệu'}/><Row a="Outfit đã lưu" b={outfits.length}/></div><div className="card panel"><h3>Trạng thái hiện tại</h3><Row a="Trạng thái" b={p?.userPresenceType===2?'Đang trong game':p?.userPresenceType===1?'Website / Studio':'Offline'}/><Row a="Game hiện tại" b={p?.lastLocation||'Không công khai'}/><Row a="Lần online cuối" b={fmtDate(p?.lastOnline)}/><Row a="Platform" b={p?.platformName||'—'}/></div></div></>}
function Avatars({data}){const outfits=data.outfits?.data||data.outfits?.outfits||[];const current=data.avatar?.assets||data.avatar?.body||[];return <><div className="notice"><b>Avatar Archive</b> · Roblox cung cấp danh sách outfits đã lưu cho user. Đây không phải snapshot của mọi lần người đó thay avatar; chỉ hiển thị outfits Roblox còn trả về qua API. </div><div className="avatarHero card"><div className="avatarPreview">{data.head?.data?.[0]?.imageUrl?<img src={data.head.data[0].imageUrl} alt="Current avatar"/>:<span>?</span>}<div className="spinHint">Avatar hiện tại · hover để xoay</div></div><div className="panelInfo"><h3>Avatar hiện tại</h3><p>Avatar definition: <b>{current.length||0}</b> component/assets được API trả về.</p><Row a="Outfits đã lưu" b={outfits.length}/><Row a="User ID" b={data.id}/><a className="outline" href={`https://www.roblox.com/users/${data.id}/profile`} target="_blank" rel="noreferrer">Xem avatar trên Roblox ↗</a></div></div><div className="sectionTitle"><h3>Toàn bộ outfits đã lưu ({outfits.length})</h3><span>{outfits.length?'API v2':'API không trả dữ liệu'}</span></div>{outfits.length?<div className="outfitGrid">{outfits.map((o,i)=><OutfitCard key={o.id||o.userOutfitId||i} o={o}/>)}</div>:<div className="card emptySmall"><h3>Chưa lấy được outfit archive</h3><p>Endpoint có thể thay đổi tham số theo khu vực/API version. Profile vẫn hoạt động bình thường.</p></div>}</>}
function OutfitCard({o}){const id=o.id||o.userOutfitId||o.outfitId;const name=o.name||o.outfitName||`Outfit #${id}`;const thumb=o.thumbnailUrl||o.imageUrl||o.thumbnail;return <div className="outfit card"><div className="outfitImg">{thumb?<img src={thumb} alt=""/>:<div className="outfitFallback">3D</div>}</div><div className="outfitBody"><b>{name}</b><small>Outfit ID: {id||'—'}</small><div className="outfitActions">{id&&<button onClick={()=>window.open(`https://www.roblox.com/catalog/${id}`,'_blank')}>Roblox ↗</button>}<button onClick={()=>window.open(`https://www.roblox.com/users/current?outfitId=${id}`,'_blank')}>Chi tiết ↗</button></div></div></div>}
function Inventory({data,query,setQuery}){const raw=data.inventory?.inventoryItems||data.inventory?.data||[];const filtered=useMemo(()=>raw.filter(x=>JSON.stringify(x).toLowerCase().includes(query.toLowerCase())),[raw,query]);if(!data.inventory)return <div className="card panel"><h3>Inventory chưa bật</h3><p>Thêm biến môi trường <code>ROBLOX_API_KEY</code> trên Vercel rồi redeploy để dùng Roblox Open Cloud Inventory API.</p><a className="outline" href="https://create.roblox.com/dashboard/credentials" target="_blank" rel="noreferrer">Mở Roblox Credentials ↗</a></div>;return <><div className="toolbar"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Tìm item, asset ID, loại…"/><span>{filtered.length} / {raw.length} items</span></div><div className="inventoryGrid">{filtered.map((x,i)=><InventoryCard key={x.id||x.assetId||i} x={x}/>)}</div></>}
function InventoryCard({x}){const id=x.assetId||x.id||x.inventoryItemAssetId;const name=x.name||x.displayName||`Asset ${id||''}`;const type=x.assetType||x.itemType||x.inventoryItemAssetType||'Item';const thumb=x.thumbnailUrl||x.imageUrl;return <div className="inventoryItem card"><div className="itemIcon">{thumb?<img src={thumb} alt=""/>:<span>◈</span>}</div><div><b>{name}</b><small>{type}</small><small>ID: {id||'—'}</small></div><a href={id?`https://www.roblox.com/catalog/${id}`:'#'} target="_blank" rel="noreferrer">↗</a></div>}
function Games({data}){const games=data.games?.data||[],fav=data.favorites?.games||data.favorites?.data||[];return <><div className="notice">ℹ Roblox không cung cấp API công khai cho <b>tổng thời gian chơi của tài khoản trên mọi game</b>. Tab này hiển thị game đã tạo và game yêu thích công khai.</div><div className="sectionTitle"><h3>Game đã tạo ({games.length})</h3></div><div className="cards">{games.map(g=><GameCard key={g.id} g={g}/>)}</div><div className="sectionTitle"><h3>Game yêu thích ({fav.length})</h3></div><div className="cards">{fav.slice(0,50).map(g=><GameCard key={g.id||g.universeId} g={g}/>)}</div></>}
function GameCard({g}){const id=g.id||g.universeId;return <a className="game" href={`https://www.roblox.com/games/${g.rootPlaceId||g.placeId||id}`} target="_blank" rel="noreferrer"><div className="gameThumb">{g.thumbnailUrl?<img src={g.thumbnailUrl} alt=""/>:<span>ROBLOX</span>}</div><div><b>{g.name||g.displayName||'Experience'}</b><small>{g.description?.slice(0,90)||'Mở game trên Roblox'}</small><small>Visits: {fmtNum(g.placeVisits||g.visits||0)} · Updated: {fmtDate(g.updated)}</small></div></a>}
function Badges({data}){const bs=data.badges?.data||[];return <><div className="sectionTitle"><h3>Roblox Badges ({bs.length})</h3></div><div className="badgeGrid">{bs.map(b=><div className="badge" key={b.id}><div className="badgeIcon">★</div><b>{b.name}</b><small>{b.description||'Không có mô tả'}</small></div>)}</div></>}
function Social({data}){const friends=data.friends?.data||[],groups=data.groups?.data||[];return <div className="grid2"><div className="card panel"><h3>Bạn bè ({friends.length}{data.friendCount?.count>100?'+':''})</h3><div className="people">{friends.map(f=><a href={`https://www.roblox.com/users/${f.id}/profile`} target="_blank" rel="noreferrer" key={f.id}><div className="mini">{f.name[0]}</div><span>{f.displayName}<small>@{f.name}</small></span></a>)}</div></div><div className="card panel"><h3>Nhóm ({groups.length})</h3><div className="groups">{groups.map(x=><div className="group" key={x.group?.id}><b>{x.group?.name}</b><small>{x.role?.name||'Member'}</small></div>)}</div></div></div>}
function History({data}){const names=data.names?.data||[];return <div className="card panel"><h3>Lịch sử username</h3>{names.length?<div className="timeline">{names.map((x,i)=><div key={i}><i></i><b>{x.name}</b><small>{x.created?fmtDate(x.created):'Roblox không cung cấp ngày đổi tên trong endpoint này'}</small></div>)}</div>:<p>Không có lịch sử username công khai.</p>}</div>}
const Stat=({n,l})=><div className="stat card"><strong>{n||'—'}</strong><span>{l}</span></div>;const Row=({a,b})=><div className="row"><span>{a}</span><b>{b||'—'}</b></div>;
