from pathlib import Path
p=Path('android/app/src/main/assets/index.html')
s=p.read_text()
s=s.replace('plusStatus().finally(render);','render(); plusStatus().then(render).catch(render);')
s=s.replace('<div class="brand">⚡ RBLXFinder <span class="badge">NOOBIE GAMING HUB</span></div>','<div class="brand"><img src="rblxfinder_icon.png" style="width:42px;height:42px;border-radius:13px;box-shadow:0 0 22px #0ea5ff66"> RBLX<span style="color:#18c9ff">Finder</span> <span class="badge">NOOBIE GAMING HUB</span></div>')
s=s.replace('<meta name="theme-color" content="#f8fafc">','<meta name="theme-color" content="#061329">')
s=s.replace('body{margin:0;background:linear-gradient(180deg,#f8fbff,#fff);color:#111827;', 'body{margin:0;background:radial-gradient(circle at 20% 0,#123c79,#061329 38%,#020914);color:#eef6ff;')
s=s.replace('.top{position:sticky;top:0;z-index:9;background:#fffffff2;', '.top{position:sticky;top:0;z-index:9;background:#030e1fee;')
s=s.replace('.tabs button{white-space:nowrap;padding:9px 12px;border-radius:11px;background:#f1f5f9;color:#334155;font-weight:800}', '.tabs button{white-space:nowrap;padding:9px 12px;border-radius:11px;background:#0d213c;color:#c7ddf3;font-weight:800;border:1px solid #23466f}')
s=s.replace('.tabs button.on{background:#111827;color:#fff}', '.tabs button.on{background:linear-gradient(135deg,#0868ff,#09bfff);color:#fff}')
s=s.replace('.card{background:#fff;border:1px solid #e5e7eb;', '.card{background:linear-gradient(180deg,#0a1d35,#07172b);border:1px solid #214466;')
s=s.replace('.input,.area{width:100%;padding:11px 12px;border:1px solid #dbe1e8;border-radius:11px;background:#fff;', '.input,.area{width:100%;padding:11px 12px;border:1px solid #2a527a;border-radius:11px;background:#06152a;color:#eef6ff;')
s=s.replace('.row{display:flex;align-items:center;gap:9px;padding:10px;border:1px solid #e8edf3;border-radius:13px;margin-top:8px}', '.row{display:flex;align-items:center;gap:9px;padding:10px;border:1px solid #1d3c5d;border-radius:13px;margin-top:8px;background:#091b31}')
s=s.replace('.stat{padding:12px;border-radius:13px;background:#f8fafc;text-align:center}', '.stat{padding:12px;border-radius:13px;background:#07182d;text-align:center;border:1px solid #214466}')
p.write_text(s)
