'use client';

import { useEffect, useState } from 'react';

export default function RobloxGamesPage(){
  const [q,setQ]=useState(''); const [games,setGames]=useState<any[]>([]); const [loading,setLoading]=useState(false); const [error,setError]=useState(''); const [thumbs,setThumbs]=useState<Record<number,string>>({});
  async function search(){
    if(!q.trim())return; setLoading(true); setError('');
    try{const r=await fetch('/api/roblox',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'games',q:q.trim()})});const d=await r.json();if(!r.ok)throw Error(d.error||'Không tìm được game');const list=d.games||d.data||[];setGames(list);if(!list.length)setError('Không tìm thấy game. Hãy thử từ khóa khác.');
      if(list.length){const t=await fetch('/api/roblox',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'thumbs',universeIds:list.map((x:any)=>x.universeId)})});const td=await t.json();const map:any={};for(const x of td.data||[])map[Number(x.universeId)]=x.thumbnails?.[0]?.imageUrl||x.imageUrl||'';setThumbs(map)}
    }catch(e){setError(e instanceof Error?e.message:'Không thể tìm game')}finally{setLoading(false)}
  }
  useEffect(()=>{const p=new URLSearchParams(location.search);const initial=p.get('q');if(initial){setQ(initial);setTimeout(search,0)}},[]);
  return <main className="page"><style>{css}</style><div className="wrap"><header><a href="/roblox">← Roblox</a><span>RBLXFinder</span></header><section className="hero"><div className="badge">ROBLOX · GAME SEARCH</div><h1>Tìm game Roblox</h1><p>Tìm game trước, sau đó chọn game để mở trang chi tiết và tìm server ít người.</p><div className="search"><input value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==='Enter'&&search()} placeholder="Ví dụ: Blox Fruits, Brookhaven, Rivals..."/><button onClick={search} disabled={loading}>{loading?'Đang tìm...':'🔎 Tìm kiếm'}</button></div></section>{error&&<div className="error">{error}</div>}<section><div className="sectionTitle"><h2>{games.length?'Kết quả tìm kiếm':'Game phổ biến / kết quả'}</h2><span>{games.length} game</span></div><div className="grid">{games.map(g=><article className="card" key={g.universeId}><div className="thumb">{thumbs[g.universeId]?<img src={thumbs[g.universeId]} alt=""/>:<div>ROBLOX</div>}</div><div className="body"><h3>{g.name}</h3><p>{g.description||'Không có mô tả.'}</p><div className="stats"><span>👥 {(g.playing||0).toLocaleString()} đang chơi</span><span>👁 {(g.visits||0).toLocaleString()} lượt chơi</span></div><a className="select" href={`/roblox/games/${g.universeId}`}>Chọn game →</a></div></article>)}</div></section></div></main>
}
const css=`*{box-sizing:border-box}.page{min-height:100vh;background:#f7f8fc;color:#171827;font-family:Inter,system-ui,sans-serif;padding:18px}.wrap{max-width:1120px;margin:auto}header{display:flex;justify-content:space-between;align-items:center;padding:8px 0 18px;font-weight:900}header a{color:#6252d8;text-decoration:none}.hero{padding:28px;border-radius:26px;background:linear-gradient(135deg,#f0edff,#eaf9ff);border:1px solid #e3e2f1;margin-bottom:22px}.badge{display:inline-block;padding:7px 10px;border-radius:999px;background:#e9e5ff;color:#5b4bd6;font-size:11px;font-weight:950}.hero h1{font-size:clamp(34px,6vw,58px);margin:12px 0 8px;letter-spacing:-2px}.hero p{color:#6f7385}.search{display:flex;gap:10px;margin-top:20px}.search input{flex:1;border:1px solid #dcddea;border-radius:14px;padding:14px;font:inherit}.search button,.select{border:0;border-radius:14px;padding:13px 17px;background:linear-gradient(135deg,#5b4bd6,#986eff);color:white;font-weight:900;text-decoration:none;cursor:pointer}.sectionTitle{display:flex;justify-content:space-between;align-items:center}.sectionTitle span{color:#777b8d}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:15px}.card{overflow:hidden;background:white;border:1px solid #e6e7ef;border-radius:20px;box-shadow:0 12px 38px #29235f0c}.thumb{aspect-ratio:16/9;background:#e9e9f0;display:grid;place-items:center;font-weight:950;color:#716d99}.thumb img{width:100%;height:100%;object-fit:cover}.body{padding:16px}.body h3{margin:0 0 7px;font-size:19px}.body p{color:#777b8d;line-height:1.45;min-height:43px}.stats{display:flex;gap:8px;flex-wrap:wrap;color:#666b7d;font-size:12px;margin:12px 0 15px}.error{background:#fff0f0;color:#b42318;padding:13px;border-radius:14px;margin-bottom:16px}@media(max-width:800px){.grid{grid-template-columns:1fr 1fr}}@media(max-width:560px){.page{padding:12px}.search{flex-direction:column}.grid{grid-template-columns:1fr}.hero{padding:21px}}`;
