'use client';

import { useState } from 'react';
const api=(body:any)=>fetch('/api/creator',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}).then(async r=>({ok:r.ok,data:await r.json()}));
export default function CreatorPage(){
 const [password,setPassword]=useState(''); const [logged,setLogged]=useState(false); const [target,setTarget]=useState(''); const [user,setUser]=useState<any>(null); const [code,setCode]=useState(''); const [msg,setMsg]=useState(''); const [busy,setBusy]=useState(false);
 const notify=(x:string)=>{setMsg(x);setTimeout(()=>setMsg(''),3500)};
 async function login(){setBusy(true);try{const r=await api({action:'creator-login',username:'khoungbell7777',password});if(!r.data?.ok)return notify(r.data?.error==='creator_auth_not_configured'?'Creator password chưa được cấu hình trên Vercel.':'Sai mật khẩu Creator.');setLogged(true);setPassword('');notify('✓ Creator đăng nhập thành công.')}finally{setBusy(false)}}
 async function resolve(){if(!target.trim())return notify('Nhập username Roblox.');setBusy(true);try{const r=await api({action:'resolve',username:target.trim()});if(!r.data?.ok)return notify('Không tìm thấy username Roblox.');setUser(r.data.user);setCode('')}finally{setBusy(false)}}
 async function grant(){if(!user)return;setBusy(true);try{const r=await api({action:'grant',username:user.name});if(!r.data?.ok)return notify(r.data?.error||'Không cấp Plus được.');notify(`✓ Đã cấp quyền Plus cho ${user.name}.`)}finally{setBusy(false)}}
 async function startVerify(){if(!user)return;setBusy(true);try{const r=await api({action:'start-verification',userId:user.id});const d=r.data;if(!d?.ok)return notify(d?.error||'Chưa được cấp Plus.');setCode(d.code);notify('Đã tạo mã xác minh.')}finally{setBusy(false)}}
 async function verify(){if(!user||!code)return;setBusy(true);try{const r=await api({action:'verify',userId:user.id,code});if(!r.data?.ok)return notify(r.data?.error==='code_not_in_profile'?'Chưa thấy mã trong Description Roblox.':r.data?.error||'Xác minh thất bại.');notify('✓ Verify thành công — Plus đã kích hoạt.')}finally{setBusy(false)}}
 const css=`*{box-sizing:border-box}body{margin:0}main{min-height:100vh;padding:22px;background:radial-gradient(circle at 10% 0,#e8e4ff,transparent 35%),#f7f8fc;color:#151622;font-family:Inter,system-ui,sans-serif}.wrap{max-width:920px;margin:auto}.top{display:flex;justify-content:space-between;gap:14px;align-items:center;flex-wrap:wrap}.brand{font-size:27px;font-weight:950}.muted{color:#717589}.card{background:#fff;border:1px solid #e7e7ef;border-radius:22px;padding:22px;margin-top:16px;box-shadow:0 15px 50px #22205a12}.input{width:100%;padding:13px;border:1px solid #d9d9e5;border-radius:12px;margin:7px 0 12px;font:inherit}.btn{border:0;border-radius:12px;padding:12px 16px;font-weight:900;cursor:pointer;background:#181827;color:#fff}.primary{background:linear-gradient(135deg,#5b4bd6,#9b6cff)}.grid{display:grid;grid-template-columns:1fr 1fr;gap:15px}.profile{display:flex;gap:13px;align-items:center;background:#faf9ff;border-radius:15px;padding:14px;margin-top:14px}.code{font:900 26px ui-monospace,monospace;letter-spacing:3px;background:#f1eeff;color:#5546c9;padding:17px;text-align:center;border-radius:14px;margin:14px 0}.notice{padding:12px;border-radius:12px;background:#eefbf3;color:#16743c;font-weight:800;margin-top:12px}.msg{position:fixed;bottom:20px;left:50%;transform:translateX(-50%);background:#171722;color:white;padding:12px 18px;border-radius:999px;font-weight:800}@media(max-width:650px){main{padding:14px}.grid{grid-template-columns:1fr}}`;
 if(!logged)return <main><style>{css}</style><div className="wrap"><div className="top"><div><div className="brand">RBLXFinder Creator</div><div className="muted">Creator-only control center</div></div><a href="/roblox" className="muted">← RBLXFinder</a></div><section className="card"><h2>Creator Login</h2><p className="muted">Creator account: <b>khoungbell7777</b>. Mật khẩu chỉ gửi tới server để kiểm tra; không lưu trong localStorage/sessionStorage.</p><input className="input" type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Mật khẩu Creator"/><button className="btn primary" disabled={busy} onClick={login}>{busy?'Đang kiểm tra...':'Đăng nhập'}</button></section></div>{msg&&<div className="msg">{msg}</div>}</main>;
 return <main><style>{css}</style><div className="wrap"><div className="top"><div><div className="brand">Creator Dashboard</div><div className="muted">Plus management · Verify · Community tools</div></div><button className="btn" onClick={()=>setLogged(false)}>Đăng xuất</button></div><section className="card"><h2>👑 Cấp Plus</h2><p className="muted">Sau khi bạn xác nhận donation, cấp quyền cho đúng Roblox User ID. Người nhận vẫn phải Verify ownership bằng Description.</p><div className="grid"><div><input className="input" value={target} onChange={e=>setTarget(e.target.value)} placeholder="Roblox username"/><button className="btn" onClick={resolve}>Tìm tài khoản</button></div><div>{user&&<div className="profile"><div><b>{user.name}</b><div className="muted">User ID: {user.id}</div></div></div>}</div></div>{user&&<><button className="btn primary" style={{marginTop:14}} disabled={busy} onClick={grant}>Cấp Plus</button><hr style={{border:0,borderTop:'1px solid #eee',margin:'22px 0'}}/><h3>🔐 Ownership Verification</h3><button className="btn" disabled={busy} onClick={startVerify}>Tạo mã xác minh</button>{code&&<><div className="code">{code}</div><p className="muted">Dán mã này vào Roblox Profile → Description của <b>{user.name}</b>, rồi bấm Verify.</p><button className="btn primary" disabled={busy} onClick={verify}>✓ Verify</button></>}</>}</section><section className="card"><h2>Power features</h2><div className="grid"><div><b>Server Power</b><p className="muted">0–1 / 0–3 / 0–5 players, auto refresh, watcher, favorites.</p></div><div><b>Game Intelligence</b><p className="muted">Thumbnails, stats, trends, comparison.</p></div><div><b>Free Fire Lab</b><p className="muted">Device presets, sensitivity calculator, preset sharing.</p></div><div><b>Moderation</b><p className="muted">Report queue, spam controls, community management.</p></div></div></section></div>{msg&&<div className="msg">{msg}</div>}</main>;
}