'use client';
import {useEffect,useMemo,useState} from 'react';
type Tab='home'|'games'|'servers'|'about'|'donate';
type User={id:number;name:string;displayName:string;avatar?:string};
type Game={universeId:number;rootPlaceId:number;name:string;playing?:number;visits?:number;favorites?:number;description?:string;created?:string;genre?:string;creator?:{name?:string}};
type Server={id:string;maxPlayers:number;playing:number};
const ROBLOX='https://www.roblox.com';
async function api(action:string,x:Record<string,unknown>={}){const r=await fetch('/api/roblox',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,...x})});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d?.error||'error');return d}
const fmt=(n?:number)=>Number(n||0).toLocaleString('vi-VN');
export default function Home(){
 const [tab,setTab]=useState<Tab>('home'),[name,setName]=useState(''),[user,setUser]=useState<User|null>(null),[pending,setPending]=useState<User|null>(null),[q,setQ]=useState(''),[games,setGames]=useState<Game[]>([]),[game,setGame]=useState<Game|null>(null),[detail,setDetail]=useState<Game|null>(null),[servers,setServers]=useState<Server[]>([]),[thumbs,setThumbs]=useState<Record<number,string>>({}),[busy,setBusy]=useState(false),[error,setError]=useState(''),[target,setTarget]=useState<Server|null>(null),[app,setApp]=useState<'vng'|'global'|null>(null),[sort,setSort]=useState<'few'|'space'>('few'),[limit,setLimit]=useState('all'),[privateEnabled,setPrivateEnabled]=useState<boolean|null>(null);
 const nav=(t:Tab)=>{history.pushState({},'',t==='home'?'/':`/${t}`);setTab(t);window.scrollTo({top:0,behavior:'smooth'})};
 useEffect(()=>{const f=()=>{const p=location.pathname.slice(1) as Tab;setTab(['games','servers','about','donate'].includes(p)?p:'home')};f();addEventListener('popstate',f);return()=>removeEventListener('popstate',f)},[]);
 useEffect(()=>{const n=localStorage.getItem('rblx_username');if(n){setName(n);api('username',{username:n}).then(d=>{const u=d?.data?.[0];if(u)setUser(u)}).catch(()=>{})}},[]);
 async function verify(){if(!name.trim())return;setBusy(true);setError('');try{const d=await api('username',{username:name.trim()});const u=d?.data?.[0];if(!u)throw Error();let a='';try{a=(await api('avatar',{userId:u.id}))?.data?.[0]?.imageUrl||''}catch{}setPending({...u,avatar:a})}catch{setError('Không tìm thấy username. Hãy kiểm tra lại.')}finally{setBusy(false)}}
 function confirm(){if(!pending)return;setUser(pending);setName(pending.name);localStorage.setItem('rblx_username',pending.name);setPending(null)}
 async function search(term=q){if(!term.trim())return;setBusy(true);setError('');nav('games');try{const d=await api('games',{query:term.trim()});const list=Array.isArray(d?.data)?d.data:[];setGames(list);const t=await api('thumbs',{universeIds:list.map((g:Game)=>g.universeId)});const m:Record<number,string>={};for(const x of t?.data||[]){const u=x?.thumbnails?.find((z:any)=>z?.imageUrl);if(u)m[Number(x.universeId)]=u.imageUrl}setThumbs(m);if(!list.length)setError('Không tìm thấy game.')}catch{setError('Không thể tìm game lúc này.')}finally{setBusy(false)}}
 async function openGame(g:Game){setGame(g);setDetail(null);setServers([]);nav('servers');setBusy(true);try{const [d,p,s]=await Promise.all([api('details',{universeId:g.universeId}),api('private',{universeId:g.universeId}),api('servers',{placeId:g.rootPlaceId})]);setDetail(d?.data?.[0]||g);setPrivateEnabled(Boolean(p));setServers(s?.data||[])}catch{setError('Không thể tải server.')}finally{setBusy(false)}}
 const shown=useMemo(()=>[...servers].filter(s=>limit==='all'||s.playing<=Number(limit)).sort((a,b)=>sort==='few'?a.playing-b.playing:(b.maxPlayers-b.playing)-(a.maxPlayers-a.playing)),[servers,sort,limit]);
 const image=(g:Game)=>thumbs[g.universeId]||'';
 const join=(s:Server)=>{setTarget(s);setApp(null)};
 const launch=(kind:'vng'|'global')=>{if(!game||!target)return;const pkg=kind==='vng'?'com.roblox.client.vnggames':'com.roblox.client';location.href=`intent://placeId=${game.rootPlaceId}&gameInstanceId=${encodeURIComponent(target.id)}#Intent;scheme=roblox;package=${pkg};end`;setTimeout(()=>location.href=`${ROBLOX}/games/start?placeId=${game.rootPlaceId}&gameInstanceId=${encodeURIComponent(target.id)}`,1200);setTarget(null);setApp(null)};
 const card=(g:Game,i:number)=><button className="game" key={g.universeId} style={{animationDelay:`${i*35}ms`}} onClick={()=>openGame(g)}><div className="thumb">{image(g)&&<img src={image(g)} alt=""/>}</div><div className="gamebody"><h3>{g.name}</h3><p>👥 {fmt(g.playing)} đang chơi</p></div></button>;
 return <main className="site"><header className="top"><div className="nav"><button className="brand" onClick={()=>nav('home')}><span className="logo">R</span><span><b>RBLXFinder</b><small>SERVER DISCOVERY</small></span></button><nav className="links">{([['home','Trang chủ'],['games','🎮 Tìm game'],['servers','🚀 Server'],['about','✨ Giới thiệu'],['donate','💜 Donate']] as [Tab,string][]).map(([k,v])=><button key={k} className={tab===k?'on':''} onClick={()=>nav(k)}>{v}</button>)}</nav><div className="online"><i/>Online</div></div></header>
 {tab==='home'&&<><section className="hero"><div><span className="badge">⚡ RBLXFINDER</span><h1>Tìm đúng server.<br/><span className="grad">Vào game nhanh hơn.</span></h1><p>Nhập username Roblox, chọn game và tìm server ít người chỉ trong vài giây.</p><div className="actions"><button className="btn primary" onClick={()=>document.getElementById('username')?.scrollIntoView({behavior:'smooth'})}>🚀 Bắt đầu ngay</button><button className="btn ghost" onClick={()=>nav('about')}>Cách hoạt động →</button></div></div><div className="preview"><div className="window"><div className="dots"><i/><i/><i/></div><div className="mock"><h3>Server Finder</h3><p>Tìm server nhanh và dễ.</p><div className="mocksearch">⌕ &nbsp; Nhập game Roblox...</div><div className="mockgrid"><div className="mockgame">🎮 Brookhaven</div><div className="mockgame">🚀 Blox Fruits</div><div className="mockgame">🌱 Grow a Garden</div><div className="mockgame">⚔️ RIVALS</div></div></div></div></div></section><section id="username" className="section"><div className="panel loginPanel"><div className="icon">👤</div><div><span className="eyebrow">BƯỚC 01</span><h2>Tiếp tục với Username Roblox</h2><p>Chỉ nhập username công khai. Không cần mật khẩu, cookie hay token.</p></div><div className="search"><input value={name} onChange={e=>setName(e.target.value)} onKeyDown={e=>e.key==='Enter'&&verify()} placeholder="Nhập username Roblox"/><button className="btn primary" onClick={verify}>{busy?'Đang kiểm tra…':'Tiếp tục →'}</button></div>{user&&<div className="verified"><b>✓ Đã xác nhận</b><strong>{user.displayName}</strong><span>@{user.name}</span></div>}{error&&<div className="error">⚠️ {error}</div>}</div></section><section className="section"><span className="eyebrow">ĐƠN GIẢN 3 BƯỚC</span><h2>Không vòng vo.</h2><div className="steps"><div className="card"><span className="stepno">01</span><div className="icon">👤</div><h3>Xác nhận username</h3><p>Tìm tài khoản Roblox công khai rồi xác nhận đúng người.</p></div><div className="card"><span className="stepno">02</span><div className="icon">🎮</div><h3>Chọn game</h3><p>Xem thumbnail, người chơi và thông tin game.</p></div><div className="card"><span className="stepno">03</span><div className="icon">🚀</div><h3>Chọn server</h3><p>Lọc server ít người và mở đúng server đã chọn.</p></div></div></section></>}
 {tab==='games'&&<section className="page"><div className="pagehead"><span className="eyebrow">ROBLOX DISCOVERY</span><h2>Tìm game</h2><p>Tìm game Roblox với thumbnail thật và thông tin trực tiếp.</p></div><div className="search"><span>⌕</span><input autoFocus value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==='Enter'&&search() } placeholder="Brookhaven, Blox Fruits, Grow a Garden…"/><button className="btn primary" onClick={()=>search()}>{busy?'Đang tìm…':'Tìm game'}</button></div><div className="chips"><button className="chip" onClick={()=>{setQ('Brookhaven');search('Brookhaven')}}>Brookhaven</button><button className="chip" onClick={()=>{setQ('Blox Fruits');search('Blox Fruits')}}>Blox Fruits</button><button className="chip" onClick={()=>{setQ('Grow a Garden');search('Grow a Garden')}}>Grow a Garden</button></div>{error&&<div className="error">⚠️ {error}</div>}<div className="games">{games.map(card)}</div>{!games.length&&!busy&&<div className="empty">🎮<h3>Tìm một game để bắt đầu</h3><p>Chọn game hoặc nhập tên game Roblox.</p></div>}</section>}
 {tab==='servers'&&<section className="page">{!game?<div className="empty">🚀<h3>Chưa chọn game</h3><p>Hãy tìm và chọn game trước.</p><button className="btn primary" onClick={()=>nav('games')}>Tìm game →</button></div>:<><button className="btn ghost" onClick={()=>nav('games')}>← Chọn game khác</button><div className="pagehead"><span className="eyebrow">SERVER BROWSER</span><h2>{detail?.name||game.name}</h2><p>{detail?.creator?.name?`Bởi ${detail.creator.name}`:'Roblox Experience'}</p></div><div className="statGrid"><div className="panel stat"><strong>{fmt(detail?.playing)}</strong><small>Đang chơi</small></div><div className="panel stat"><strong>{fmt(detail?.visits)}</strong><small>Lượt chơi</small></div><div className="panel stat"><strong>{fmt(detail?.favorites)}</strong><small>Yêu thích</small></div><div className="panel stat"><strong>{fmt(detail?.maxPlayers)}</strong><small>Max/server</small></div></div><div className="toolbar panel"><select value={sort} onChange={e=>setSort(e.target.value as 'few'|'space')}><option value="few">Ít người nhất</option><option value="space">Nhiều chỗ trống nhất</option></select><select value={limit} onChange={e=>setLimit(e.target.value)}><option value="all">Tất cả</option><option value="5">≤ 5 người</option><option value="10">≤ 10 người</option><option value="20">≤ 20 người</option></select><button className="btn ghost" onClick={()=>openGame(game)}>↻ Làm mới</button></div>{busy&&!detail?<div className="empty">⏳<h3>Đang quét server…</h3></div>:shown.map((s,i)=><article className="server panel" key={s.id}><div className="rank">{i+1}</div><div className="serverinfo"><b>Server #{i+1}</b><small>🟢 {Math.max(0,s.maxPlayers-s.playing)} chỗ trống · ID {s.id.slice(0,8)}</small><div className="bar"><i style={{width:`${Math.min(100,s.playing/s.maxPlayers*100)}%`}}/></div></div><div className="count"><strong>{s.playing}</strong><small> / {s.maxPlayers}</small></div><button className="btn primary" onClick={()=>join(s)}>Tham gia →</button></article>)}{!busy&&!shown.length&&<div className="empty">🔎<h3>Không có server phù hợp</h3></div>}</>}</section>}
 {tab==='about'&&<section className="page"><div className="pagehead"><span className="badge">ABOUT RBLXFINDER</span><h2>Được tạo để<br/><span className="grad">tìm server dễ hơn.</span></h2><p>RBLXFinder giúp người chơi Roblox tìm game, xem thông tin và lọc server công khai nhanh chóng.</p></div><div className="steps"><div className="card"><div className="icon">🔎</div><h3>Tìm game</h3><p>Tìm kiếm game Roblox bằng tên.</p></div><div className="card"><div className="icon">📊</div><h3>Xem server</h3><p>Ưu tiên server ít người hoặc nhiều chỗ trống.</p></div><div className="card"><div className="icon">🚀</div><h3>Vào nhanh</h3><p>Chọn ứng dụng Roblox rồi mở đúng server.</p></div></div><div className="panel profile"><div className="creatoravatar">K</div><div><h2>khoungbell7777</h2><p>Creator của RBLXFinder</p><button className="btn primary" onClick={()=>window.open(`${ROBLOX}/users/profile?username=khoungbell7777`,'_blank')}>Follow ↗</button></div></div></section>}
 {tab==='donate'&&<section className="page"><div className="pagehead"><span className="badge">SUPPORT CREATOR</span><h2>Ủng hộ <span className="grad">RBLXFinder.</span></h2><p>Nếu website hữu ích, bạn có thể ủng hộ creator.</p></div><div className="donates"><div className="card donate"><div className="donateicon">🎟️</div><h2>Game Pass</h2><p>Ủng hộ qua Game Pass Roblox.</p><button className="btn primary" onClick={()=>window.open(`${ROBLOX}/games/`,'_blank')}>Mở Roblox →</button></div><div className="card donate"><div className="donateicon">💜</div><h2>Roblox Plus</h2><p>Khám phá Roblox Plus và các quyền lợi dành cho người chơi.</p><button className="btn ghost" onClick={()=>window.open(ROBLOX,'_blank')}>Roblox ↗</button></div></div></section>}
 {pending&&<div className="modalbg"><div className="modal"><div className="modaltop">✨<button className="close" onClick={()=>setPending(null)}>×</button></div><h2>Có phải username của bạn?</h2><div className="user"><img src={pending.avatar||`https://thumbnails.roblox.com/v1/users/avatar-headshot?userIds=${pending.id}&size=150x150&format=Png&isCircular=true`} alt=""/><div><b>{pending.displayName}</b><span>@{pending.name}</span><small>✓ Username Roblox đã được tìm thấy</small></div></div><div className="modalactions"><button className="btn ghost" onClick={()=>setPending(null)}>Không phải</button><button className="btn primary" onClick={confirm}>✓ Đúng, tiếp tục</button></div></div></div>}
 {target&&<div className="modalbg"><div className="modal"><div className="modaltop">🚀<button className="close" onClick={()=>{setTarget(null);setApp(null)}}>×</button></div>{!app?<><h2>Chọn ứng dụng Roblox</h2><p style={{color:'#777b8d'}}>Chọn phiên bản muốn dùng để mở server.</p><div className="apps"><button onClick={()=>setApp('vng')}><em>🇻🇳</em><div><b>Roblox VN</b><small>VNG Games</small></div></button><button onClick={()=>setApp('global')}><em>🌎</em><div><b>Roblox Global</b><small>Phiên bản quốc tế</small></div></button></div><button className="btn ghost" style={{width:'100%'}} onClick={()=>setTarget(null)}>Hủy</button></>:<><h2>{app==='vng'?'🇻🇳 Roblox VN':'🌎 Roblox Global'}</h2><p style={{color:'#777b8d'}}>Bạn sắp mở server đã chọn.</p><button className="btn primary" style={{width:'100%'}} onClick={()=>launch(app)}>🚀 Mở Roblox</button><button className="btn ghost" style={{width:'100%',marginTop:8}} onClick={()=>setApp(null)}>← Chọn lại</button></>}</div></div>}
 </main>}
