'use client';

import { useEffect, useState } from 'react';

export default function GameServers({params}:{params:{universeId:string}}){
 const [game,setGame]=useState<any>(null);const [servers,setServers]=useState<any[]>([]);const [loading,setLoading]=useState(true);const [refresh,setRefresh]=useState(false);const id=Number(params.universeId);
 async function load(){setLoading(true);try{const d=await (await fetch('/api/roblox',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'details',universeId:id})})).json();setGame(d?.data?.[0]||null);const s=await (await fetch('/api/roblox',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'servers',universeId:id})})).json();setServers((s.data||[]).sort((a:any,b:any)=>(a.playing||0)-(b.playing||0)))}finally{setLoading(false)}}
 useEffect(()=>{if(Number.isInteger(id)&&id>0)load()},[id]);
 async function refreshServers(){setRefresh(true);try{const s=await (await fetch('/api/roblox',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'servers',universeId:id})})).json();setServers((s.data||[]).sort((a:any,b:any)=>(a.playing||0)-(b.playing||0)))}finally{setRefresh(false)}}
 return <main className="page"><style>{css}</style><div className="wrap"><header><a href="/roblox/games">← Tìm game</a><a href="/roblox">Roblox</a></header>{game&&<section className="hero"><div className="badge">GAME ĐÃ CHỌN</div><h1>{game.name}</h1><p>{game.description||'Không có mô tả.'}</p><div className="stats"><span>👥 {(game.playing||0).toLocaleString()} đang chơi</span><span>👁 {(game.visits||0).toLocaleString()} visits</span><span>🆔 Universe {id}</span></div><div className="actions"><a className="btn" target="_blank" rel="noreferrer" href={`https://www.roblox.com/games/${game.rootPlaceId}`}>Mở game Roblox</a><button className="btn primary" onClick={refreshServers}>{refresh?'Đang cập nhật...':'↻ Cập nhật server'}</button></div></section>}<section className="card"><div className="title"><div><div className="badge">SERVER FINDER</div><h2>Server ít người</h2><p>Danh sách được sắp xếp từ ít người → nhiều người. Không teleport tự động.</p></div><b>{servers.length} server</b></div>{loading?<div className="empty">Đang tải game và server...</div>:!servers.length?<div className="empty">Không lấy được server công khai lúc này. Hãy thử cập nhật lại.</div>:<div className="servers">{servers.map((s:any,i)=><div className="server" key={s.id}><div><b>#{i+1} · {s.playing||0}/{s.maxPlayers||0} người</b><div className="muted">Server ID: {s.id}</div><div className="muted">Ping: {s.ping||'—'} · FPS: {s.fps||'—'}</div></div><button className="btn" onClick={()=>navigator.clipboard?.writeText(s.id)}>Copy ID</button></div>)}</div>}</section></div></main>
}
const css=`*{box-sizing:border-box}.page{min-height:100vh;background:#f7f8fc;color:#171827;font-family:Inter,system-ui,sans-serif;padding:18px}.wrap{max-width:1050px;margin:auto}header{display:flex;justify-content:space-between;padding:8px 0 18px;font-weight:900}header a{color:#6252d8;text-decoration:none}.hero{padding:28px;border-radius:26px;background:linear-gradient(135deg,#f0edff,#eaf9ff);border:1px solid #e3e2f1;margin-bottom:18px}.badge{display:inline-block;padding:7px 10px;border-radius:999px;background:#e9e5ff;color:#5b4bd6;font-size:11px;font-weight:950}.hero h1{font-size:clamp(32px,6vw,54px);margin:12px 0 8px;letter-spacing:-2px}.hero p,.muted{color:#777b8d;line-height:1.5}.stats{display:flex;gap:10px;flex-wrap:wrap;color:#666b7d;font-size:13px}.actions{display:flex;gap:9px;flex-wrap:wrap;margin-top:18px}.card{background:#fff;border:1px solid #e6e7ef;border-radius:22px;padding:20px;box-shadow:0 12px 38px #29235f0c}.title{display:flex;justify-content:space-between;gap:15px;align-items:flex-start}.title h2{margin:10px 0 4px}.servers{margin-top:10px}.server{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:14px 0;border-top:1px solid #eee}.btn{border:1px solid #dedee9;border-radius:12px;padding:11px 15px;background:#fff;color:#333;font-weight:900;cursor:pointer;text-decoration:none;display:inline-block}.btn.primary{background:linear-gradient(135deg,#5b4bd6,#986eff);border:0;color:#fff}.empty{padding:30px;text-align:center;color:#777b8d}@media(max-width:600px){.page{padding:12px}.hero,.card{padding:17px}.title{display:block}.server{align-items:flex-start}}`;
