import { NextRequest, NextResponse } from 'next/server';
const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Methods':'POST, OPTIONS','Access-Control-Allow-Headers':'Content-Type, Authorization'};
export async function OPTIONS(){return new NextResponse(null,{status:204,headers:cors})}
const out=(d:any,s=200)=>NextResponse.json(d,{status:s,headers:cors});
async function get(url:string,init?:RequestInit){const r=await fetch(url,{...init,cache:'no-store',headers:{Accept:'application/json','User-Agent':'RBLXFinder/8.0',...(init?.headers||{})}});const t=await r.text();let d:any;try{d=JSON.parse(t)}catch{d={message:t}}if(!r.ok)throw new Error(`${r.status}: ${d?.message||'Roblox API error'}`);return d}
function gamesFrom(x:any){const a:any[]=[];for(const g of x?.searchResults||[])for(const v of g?.contents||[])if(v)a.push(v);const src=a.length?a:(x?.games||x?.data||[]),seen=new Set<number>();return (Array.isArray(src)?src:[]).map((v:any)=>({universeId:Number(v.universeId??v.id),rootPlaceId:Number(v.rootPlaceId??v.placeId),name:String(v.name||v.title||''),description:v.description||'',playing:Number(v.playerCount??v.playing??0)||0,visits:Number(v.visits??0)||0,favorites:Number(v.totalUpVotes??v.favorites??0)||0})).filter((v:any)=>v.universeId>0&&v.rootPlaceId>0&&v.name&&!seen.has(v.universeId)&&seen.add(v.universeId));}
async function enrich(a:any[]){const ids=a.map(v=>v.universeId).slice(0,50);if(!ids.length)return a;let d:any={data:[]},t:any={data:[]};try{d=await get(`https://games.roblox.com/v1/games?universeIds=${ids.join(',')}`)}catch{}try{t=await get(`https://thumbnails.roblox.com/v1/games/multiget/thumbnails?universeIds=${ids.join(',')}&countPerUniverse=1&defaults=true&size=768x432&format=Webp&isCircular=false`)}catch{}const dm=new Map((d.data||[]).map((v:any)=>[Number(v.id),v])),tm=new Map((t.data||[]).map((v:any)=>[Number(v.targetId),v.imageUrl]));return a.map(v=>{const z:any=dm.get(v.universeId)||{};return {...v,name:z.name||v.name,description:z.description||v.description,rootPlaceId:Number(z.rootPlaceId||v.rootPlaceId),playing:Number(z.playing??v.playing??0),visits:Number(z.visits??v.visits??0),favorites:Number(z.favoritesCount??v.favorites??0),thumbnailUrl:tm.get(v.universeId)||''}})}
export async function POST(req:NextRequest){try{const b=await req.json(),a=b.action;
if(a==='username'){const u=String(b.username||'').trim();if(!u)return out({error:'Username required'},400);const d=await get('https://users.roblox.com/v1/usernames/users',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({usernames:[u],excludeBannedUsers:false})});const x=d.data?.[0];if(!x)return out({error:'User not found'},404);let avatarUrl='';try{avatarUrl=(await get(`https://thumbnails.roblox.com/v1/users/avatar-headshot?userIds=${x.id}&size=150x150&format=Png&isCircular=false`)).data?.[0]?.imageUrl||''}catch{}return out({id:x.id,name:x.name,displayName:x.displayName,avatarUrl,profileUrl:`https://www.roblox.com/users/${x.id}/profile`})}
if(a==='games'){const q=String(b.query||b.q||'').trim();if(!q)return out({data:[],games:[]});let all:any[]=[],token='',session=crypto.randomUUID();for(let i=0;i<3;i++){try{const d=await get(`https://apis.roblox.com/search-api/omni-search?searchQuery=${encodeURIComponent(q)}&pageToken=${encodeURIComponent(token)}&sessionId=${session}&pageType=all`);all.push(...gamesFrom(d));const n=d.nextPageToken||'';if(!n||n===token)break;token=n}catch{break}}all=await enrich(all.slice(0,60));const seen=new Set<number>();all=all.filter(v=>!seen.has(v.universeId)&&seen.add(v.universeId));return out({data:all,games:all})}
if(a==='servers'){let place=Number(b.placeId),universe=Number(b.universeId);if(!place&&universe){const d=await get(`https://games.roblox.com/v1/games?universeIds=${universe}`);place=Number(d.data?.[0]?.rootPlaceId)}if(!place)return out({error:'Invalid game'},400);let cur='',all:any[]=[],seen=new Set<string>();for(let i=0;i<5;i++){const p=new URLSearchParams({sortOrder:'1',excludeFullGames:'true',limit:'100'});if(cur)p.set('cursor',cur);const d=await get(`https://games.roblox.com/v1/games/${place}/servers/Public?${p}`);for(const s of d.data||[])if(s.id&&!seen.has(s.id)){seen.add(s.id);all.push(s)}cur=d.nextPageCursor||'';if(!cur)break}all.sort((x,y)=>(x.playing||0)-(y.playing||0));return out({data:all.slice(0,500),placeId:place})}
if(a==='avatar'){const id=Number(b.userId);return out(await get(`https://thumbnails.roblox.com/v1/users/avatar-headshot?userIds=${id}&size=150x150&format=Png&isCircular=true`))}
if(a==='details'){const id=Number(b.universeId);return out(await get(`https://games.roblox.com/v1/games?universeIds=${id}`))}
if(a==='thumbs'){const ids=(b.universeIds||[]).map(Number).filter((x:number)=>x>0).slice(0,50);return out(await get(`https://thumbnails.roblox.com/v1/games/multiget/thumbnails?universeIds=${ids.join(',')}&countPerUniverse=1&defaults=true&size=768x432&format=Webp&isCircular=false`))}
if(a==='private'){const id=Number(b.universeId);return out(await get(`https://games.roblox.com/v1/private-servers/enabled-in-universe/${id}`))}
return out({error:'Unknown action'},400)}catch(e){return out({error:e instanceof Error?e.message:'Roblox API failed'},502)}}
