'use client';
import {useState} from 'react';
const api=(body:any)=>fetch('/api/creator',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}).then(async r=>({ok:r.ok,data:await r.json()}));
export default function Plus(){
 const [username,setUsername]=useState('');const [user,setUser]=useState<any>();const [code,setCode]=useState('');const [msg,setMsg]=useState('');const [busy,setBusy]=useState(false);
 const notify=(x:string)=>{setMsg(x);setTimeout(()=>setMsg(''),3500)};
 async function find(){if(!username.trim())return;setBusy(true);try{const r=await api({action:'resolve',username});if(!r.data?.ok)return notify('Không tìm thấy username Roblox.');setUser(r.data.user);const s=await api({action:'status',userId:r.data.user.id});if(s.data?.verified)notify('✓ Tài khoản đã Verify Plus.')}finally{setBusy(false)}}
 async function start(){if(!user)return;setBusy(true);try{const r=await api({action:'start-verification',userId:user.id});if(!r.data?.ok)return notify(r.data?.error||'Bạn chưa được Creator cấp Plus.');setCode(r.data.code)}finally{setBusy(false)}}
 async function verify(){if(!user||!code)return;setBusy(true);try{const r=await api({action:'verify',userId:user.id,code});notify(r.data?.ok?'✓ Verify thành công! Plus đã mở.':r.data?.error==='code_not_in_profile'?'Chưa thấy mã trong Description Roblox.':r.data?.error||'Verify thất bại.')}finally{setBusy(false)}}
 const css=`body{margin:0}.wrap{max-width:1100px;margin:auto}.top{display:flex;justify-content:space-between;align-items:center;gap:12px}.brand{font-size:28px;font-weight:950}.hero{background:linear-gradient(135deg,#5545d8,#8f72ff);color:white;border-radius:28px;padding:32px;margin:20px 0}.hero h1{font-size:42px;margin:0 0 8px}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(230px,1fr));gap:14px}.card{background:#fff;border:1px solid #e6e7ef;border-radius:20px;padding:20px;box-shadow:0 12px 40px #1718270d}.input{width:100%;box-sizing:border-box;padding:13px;border:1px solid #d9dbe5;border-radius:12px;margin:8px 0 12px;font:inherit}.btn{border:0;border-radius:12px;padding:12px 16px;font-weight:900;background:#171827;color:#fff;cursor:pointer}.primary{background:#6655dd}.code{font:900 25px ui-monospace,monospace;text-align:center;letter-spacing:3px;background:#f1efff;color:#5545cf;padding:17px;border-radius:14px;margin:14px 0}.muted{color:#717589}.hero .muted{color:#eee}.msg{position:fixed;bottom:20px;left:50%;transform:translateX(-50%);background:#171827;color:#fff;padding:12px 18px;border-radius:999px;font-weight:800}.tag{display:inline-block;padding:7px 10px;border-radius:999px;background:#efedff;color:#5d4fd2;font-weight:900;font-size:12px}.free{border:1px solid #e4e5ee;background:#fafbff}.power{border-left:4px solid #6555dd}.off{opacity:.7}@media(max-width:600px){main{padding:12px!important}.hero h1{font-size:32px}}`;
 return <main style={{minHeight:'100vh',background:'#f6f7fb',color:'#171827',fontFamily:'Inter,system-ui,sans-serif',padding:20}}><style>{css}</style><div className="wrap">
  <div className="top"><div className="brand">RBLXFinder</div><a href="/roblox" className="muted">← Roblox</a></div>
  <section className="hero"><span className="tag" style={{background:'#ffffff22',color:'#fff'}}>ROBLOX ONLY</span><h1>RBLXFinder Plus</h1><p className="muted">Plus chỉ dành cho Roblox. Free Fire hoàn toàn không có Plus và các tính năng Free Fire quan trọng vẫn miễn phí.</p></section>
  <div className="grid">
   <div className="card power"><h2>⚡ Server Power</h2><p>Ưu tiên lọc server ít người, 0–1 / 0–3 / 0–5, tự làm mới, theo dõi server và lưu server yêu thích.</p></div>
   <div className="card power"><h2>📊 Game Intelligence</h2><p>Thumbnail, thống kê nâng cao, player count, visits, creator, ID, theo dõi game và so sánh game.</p></div>
   <div className="card power"><h2>🔎 Profile Intelligence</h2><p>Tra User ID, avatar, Display Name và các dữ liệu Roblox công khai được hỗ trợ.</p></div>
   <div className="card power"><h2>🎛️ Personal Tools</h2><p>Lịch sử tìm kiếm, game/server yêu thích, shortcut và tùy chỉnh giao diện Plus.</p></div>
  </div>
  <section className="card" style={{marginTop:16}}><h2>Free vẫn mạnh</h2><p className="muted">RBLXFinder Free vẫn có Username Lookup, tìm game, thumbnail game, tìm server ít người, cộng đồng, like/bình luận và các công cụ Roblox cơ bản. Plus chỉ mở thêm các công cụ nâng cao và tiện ích tự động.</p></section>
  <section className="card" style={{marginTop:16}}><h2>🔐 Verify Plus</h2><p className="muted">Nhập username Roblox đã được Creator cấp Plus. Hệ thống dùng User ID và kiểm tra Description public.</p><input className="input" value={username} onChange={e=>setUsername(e.target.value)} placeholder="Roblox username"/><button className="btn primary" disabled={busy} onClick={find}>Tìm tài khoản</button>{user&&<div style={{marginTop:16}}><b>{user.name}</b><div className="muted">User ID: {user.id}</div><button className="btn" style={{marginTop:12}} disabled={busy} onClick={start}>Tạo mã xác minh</button>{code&&<><div className="code">{code}</div><p className="muted">Dán mã vào Roblox Profile → Description của <b>{user.name}</b>.</p><button className="btn primary" disabled={busy} onClick={verify}>✓ Verify và mở Plus</button></>}</div>}</section>
 </div>{msg&&<div className="msg">{msg}</div>}</main>
}