'use client';

import { useEffect, useMemo, useState } from 'react';

type RobloxUser = { id:number; name:string; displayName:string; avatarUrl?:string; profileUrl?:string };
type Game = { id:number; universeId?:number; name:string; description?:string; playing?:number; visits?:number; favorites?:number; thumbnailUrl?:string };

const ffPresets = [
  ['OPPO A9 2020',184,47,440],['iPhone 11',188,48,0],['iPhone 13',194,49,0],['iPhone 15 Pro',200,50,0],
  ['Samsung A54',192,49,480],['Samsung S24',192,49,520],['Xiaomi Redmi Note 13',182,48,480],['vivo V40',194,50,520],
  ['realme 12',194,50,520]
];

export default function ToolsHub(){
  const [tab,setTab]=useState<'home'|'roblox'|'freefire'|'daily'|'compare'>('home');
  const [rbName,setRbName]=useState(''); const [user,setUser]=useState<RobloxUser|null>(null); const [busy,setBusy]=useState(false); const [err,setErr]=useState('');
  const [gameQ,setGameQ]=useState(''); const [games,setGames]=useState<Game[]>([]); const [serverQ,setServerQ]=useState(''); const [servers,setServers]=useState<any[]>([]);
  const [compare,setCompare]=useState<Game[]>([]); const [preset,setPreset]=useState(ffPresets[0]); const [aim,setAim]=useState(0); const [shots,setShots]=useState(0); const [score,setScore]=useState(0);
  const [xp,setXp]=useState(0); const [streak,setStreak]=useState(1); const [saved,setSaved]=useState<string[]>([]);
  useEffect(()=>{setXp(Number(localStorage.getItem('rblx_xp')||0));setStreak(Number(localStorage.getItem('rblx_streak')||1));setSaved(JSON.parse(localStorage.getItem('rblx_saved_games')||'[]'));},[]);
  const addXp=(n:number)=>{setXp(x=>{const v=x+n;localStorage.setItem('rblx_xp',String(v));return v})};
  const searchUser=async()=>{if(!rbName.trim())return;setBusy(true);setErr('');try{const r=await fetch('/api/roblox',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'username',username:rbName.trim()})});const d=await r.json();if(!r.ok)throw Error();setUser(d);addXp(10)}catch{setErr('Không tìm thấy username Roblox.')}finally{setBusy(false)}};
  const searchGames=async()=>{if(!gameQ.trim())return;setBusy(true);setErr('');try{const r=await fetch('/api/roblox',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'games',q:gameQ.trim()})});const d=await r.json();const list=Array.isArray(d.games)?d.games:Array.isArray(d.data)?d.data:[];setGames(list);addXp(15)}catch{setErr('Không tải được danh sách game.')}finally{setBusy(false)}};
  const searchServers=async()=>{const id=Number(serverQ);if(!id)return;setBusy(true);try{const r=await fetch('/api/roblox',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'servers',universeId:id})});const d=await r.json();setServers(Array.isArray(d.data)?d.data:[]);addXp(10)}catch{setErr('Không tải được server.')}finally{setBusy(false)}};
  const toggleCompare=(g:Game)=>setCompare(x=>x.some(a=>a.id===g.id)?x.filter(a=>a.id!==g.id):x.length<4?[...x,g]:x);
  const filteredServers=useMemo(()=>servers.slice().sort((a,b)=>(a.playing??999)-(b.playing??999)),[servers]);
  const shoot=()=>{setShots(s=>s+1);const hit=Math.random()>.25; if(hit){setAim(a=>a+1);setScore(s=>Math.min(100,s+4));addXp(2)}else setScore(s=>Math.max(0,s-1))};
  const saveGame=(g:Game)=>{const key=String(g.id);setSaved(x=>{const n=x.includes(key)?x.filter(a=>a!==key):[...x,key];localStorage.setItem('rblx_saved_games',JSON.stringify(n));return n});addXp(3)};
  return <main style={{minHeight:'100vh',background:'linear-gradient(180deg,#f8fbff,#fff)',color:'#111827',fontFamily:'Inter,system-ui,sans-serif'}}>
    <header style={{position:'sticky',top:0,zIndex:20,background:'#ffffffdd',backdropFilter:'blur(16px)',borderBottom:'1px solid #e5e7eb'}}><div style={{maxWidth:1180,margin:'auto',padding:'14px 18px',display:'flex',alignItems:'center',gap:12,flexWrap:'wrap'}}><b style={{fontSize:22}}>⚡ RBLXFinder</b><span style={{fontSize:12,padding:'5px 9px',borderRadius:99,background:'#eff6ff',color:'#2563eb',fontWeight:800}}>GAME HUB</span><nav style={{display:'flex',gap:7,marginLeft:'auto',overflowX:'auto'}}>{[['home','Home'],['roblox','Roblox'],['freefire','Free Fire'],['daily','Daily'],['compare','Compare']].map(([k,v])=><button key={k} onClick={()=>setTab(k as any)} style={{border:0,borderRadius:10,padding:'9px 12px',background:tab===k?'#111827':'#f1f5f9',color:tab===k?'#fff':'#334155',fontWeight:800}}>{v}</button>)}</nav></div></header>
    <div style={{maxWidth:1180,margin:'auto',padding:'28px 18px 80px'}}>
      {err&&<div style={{padding:12,marginBottom:16,borderRadius:14,background:'#fef2f2',color:'#b91c1c',fontWeight:700}}>{err}</div>}
      {tab==='home'&&<><section style={{padding:'30px 24px',borderRadius:26,background:'linear-gradient(135deg,#111827,#2563eb)',color:'#fff',boxShadow:'0 20px 50px #1e3a8a22'}}><div style={{fontSize:12,fontWeight:900,letterSpacing:'.12em',opacity:.75}}>NOOBIE GAMING TOOLS</div><h1 style={{fontSize:'clamp(30px,6vw,54px)',lineHeight:1.02,margin:'9px 0'}}>Một nơi cho Roblox + Free Fire.</h1><p style={{maxWidth:700,opacity:.86,lineHeight:1.6}}>Server Finder, Profile Scanner, Game Intelligence, Sensitivity Lab, Aim Challenge, Compare, Favorites và hệ thống XP — tối ưu cho cả điện thoại.</p><div style={{display:'flex',gap:9,flexWrap:'wrap',marginTop:18}}><button onClick={()=>setTab('roblox')} style={primary}>🔎 Roblox Tools</button><button onClick={()=>setTab('freefire')} style={light}>🎯 Free Fire Lab</button></div></section><div style={grid}><Card title="🏆 Level & XP"><b style={{fontSize:30}}>{Math.floor(xp/100)+1}</b><p style={muted}>{xp % 100}/100 XP · streak 🔥 {streak} ngày</p></Card><Card title="⭐ Saved Games"><b style={{fontSize:30}}>{saved.length}</b><p style={muted}>Lưu game ngay trên thiết bị</p></Card><Card title="🤖 AI Assistant"><b>Luôn sẵn sàng</b><p style={muted}>Hỏi về Roblox hoặc Free Fire</p></Card></div></>}
      {tab==='roblox'&&<><h2>🎮 Roblox Power Tools</h2><div style={grid}><Card title="👤 Profile Scanner"><div style={{display:'flex',gap:8}}><input value={rbName} onChange={e=>setRbName(e.target.value)} placeholder="Username Roblox" style={input}/><button onClick={searchUser} style={dark}>{busy?'...':'Tìm'}</button></div>{user&&<div style={{marginTop:14,padding:14,borderRadius:16,background:'#f8fafc'}}><b>{user.displayName}</b> <span style={{color:'#64748b'}}>@{user.name}</span><div style={muted}>User ID: {user.id}</div>{user.profileUrl&&<a href={user.profileUrl} target="_blank">Mở profile Roblox →</a>}</div>}</Card><Card title="🎮 Game Intelligence"><div style={{display:'flex',gap:8}}><input value={gameQ} onChange={e=>setGameQ(e.target.value)} placeholder="Tên game" style={input}/><button onClick={searchGames} style={dark}>{busy?'...':'Tìm'}</button></div><div style={{marginTop:12,display:'grid',gap:9}}>{games.slice(0,12).map(g=><div key={g.id} style={row}><div style={{width:58,height:58,borderRadius:12,overflow:'hidden',background:'#e2e8f0'}}>{g.thumbnailUrl&&<img src={g.thumbnailUrl} alt="" style={{width:'100%',height:'100%',objectFit:'cover'}}/>}</div><div style={{flex:1}}><b>{g.name}</b><div style={muted}>👥 {(g.playing??0).toLocaleString()} · ⭐ {(g.favorites??0).toLocaleString()}</div></div><button onClick={()=>toggleCompare(g)} style={small}>{compare.some(a=>a.id===g.id)?'✓ So sánh':'＋'}</button><button onClick={()=>saveGame(g)} style={small}>{saved.includes(String(g.id))?'★':'☆'}</button></div>)}</div></Card><Card title="🖥️ Low-Pop Server Finder"><p style={muted}>Nhập Universe ID. Free vẫn được lọc server cơ bản.</p><div style={{display:'flex',gap:8}}><input value={serverQ} onChange={e=>setServerQ(e.target.value)} placeholder="Universe ID" inputMode="numeric" style={input}/><button onClick={searchServers} style={dark}>{busy?'...':'Tìm server'}</button></div><div style={{marginTop:12,display:'grid',gap:7}}>{filteredServers.slice(0,15).map((s,i)=><div key={s.id||i} style={row}><b style={{width:70}}>{s.playing??'?'} / {s.maxPlayers??'?'}</b><span style={{flex:1,fontSize:12,color:'#64748b'}}>{s.id||'Server'}</span><button onClick={()=>navigator.clipboard?.writeText(s.id||'')} style={small}>Copy ID</button></div>)}</div></Card></div></>}
      {tab==='freefire'&&<><h2>🎯 Free Fire Sensitivity + Aim Lab</h2><div style={grid}><Card title="📱 Device Preset"><select value={preset[0]} onChange={e=>setPreset(ffPresets.find(p=>p[0]===e.target.value)||ffPresets[0])} style={input}>{ffPresets.map(p=><option key={p[0]}>{p[0]}</option>)}</select><div style={grid2}><Stat label="General" value={preset[1]}/><Stat label="Red Dot" value={preset[2]}/><Stat label="DPI" value={preset[3]||'Auto'}/></div><button onClick={()=>{navigator.clipboard?.writeText(`Free Fire ${preset[0]} | General ${preset[1]} | Red Dot ${preset[2]} | DPI ${preset[3]||'Auto'}`);addXp(5)}} style={dark}>📋 Copy preset</button></Card><Card title="🎯 Aim Challenge"><p style={muted}>Bấm mục tiêu giả lập để luyện phản xạ. Mỗi hit +4 điểm.</p><div style={{height:220,borderRadius:20,background:'radial-gradient(circle,#dbeafe,#f8fafc)',display:'grid',placeItems:'center',position:'relative'}}><button onClick={shoot} aria-label="target" style={{width:70,height:70,borderRadius:'50%',border:'8px solid #ef4444',background:'#fff',fontSize:24}}>🎯</button></div><div style={grid2}><Stat label="Score" value={score}/><Stat label="Hits" value={aim}/><Stat label="Shots" value={shots}/></div></Card><Card title="🎛️ HUD Builder"><p style={muted}>Kích thước nút bắn</p><input type="range" min="35" max="65" value={preset[2]} onChange={e=>setPreset([preset[0],preset[1],Number(e.target.value),preset[3]])} style={{width:'100%'}}/><div style={{display:'grid',placeItems:'center',height:120,background:'#0f172a',borderRadius:18,marginTop:10}}><div style={{width:preset[2]+20,height:preset[2]+20,borderRadius:'50%',background:'#ef4444',display:'grid',placeItems:'center',color:'#fff',fontWeight:900}}>FIRE</div></div></Card></div></>}
      {tab==='daily'&&<><h2>🏆 Daily Challenge</h2><div style={grid}><Card title="🔥 Hôm nay"><h3>Roblox Hunter</h3><p style={muted}>Tìm 2 game + 1 server ít người.</p><button onClick={()=>{addXp(25);alert('Hoàn thành! +25 XP')}} style={dark}>Hoàn thành thử thách</button></Card><Card title="🎯 Free Fire Aim"><h3>10 lần bắn</h3><p style={muted}>Mục tiêu: Score ≥ 25.</p><button onClick={()=>{setTab('freefire');addXp(5)}} style={dark}>Chơi ngay</button></Card><Card title="🏅 Achievements"><p>🔎 Profile Detective · 🎮 Game Hunter · 🖥️ Server Hunter · 🎯 Aim Rookie · 🔥 Daily Streak</p></Card></div></>}
      {tab==='compare'&&<><h2>⚖️ Game Compare</h2><p style={muted}>Chọn tối đa 4 game ở Roblox Tools.</p>{compare.length===0?<Card title="Chưa có game">Vào Roblox → Game Intelligence → bấm ＋ So sánh.</Card>:<div style={{overflowX:'auto',background:'#fff',border:'1px solid #e5e7eb',borderRadius:18}}><table style={{width:'100%',borderCollapse:'collapse'}}><thead><tr><th style={th}>Chỉ số</th>{compare.map(g=><th key={g.id} style={th}>{g.name}</th>)}</tr></thead><tbody>{[['Players','playing'],['Visits','visits'],['Favorites','favorites'],['ID','id']].map(([a,k])=><tr key={k}><td style={th}>{a}</td>{compare.map(g=><td key={g.id} style={td}>{Number((g as any)[k]||0).toLocaleString()}</td>)}</tr>)}</tbody></table></div>}</>}
    </div>
  </main>
}

const grid:React.CSSProperties={display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(280px,1fr))',gap:16,marginTop:18};
const grid2:React.CSSProperties={display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:8,margin:'14px 0'};
const input:React.CSSProperties={width:'100%',boxSizing:'border-box',border:'1px solid #dbe1e8',borderRadius:12,padding:'11px 12px',background:'#fff',color:'#111827'};
const primary:React.CSSProperties={border:0,borderRadius:12,padding:'12px 16px',background:'#fff',color:'#111827',fontWeight:900};
const light:React.CSSProperties={border:'1px solid #ffffff55',borderRadius:12,padding:'12px 16px',background:'#ffffff18',color:'#fff',fontWeight:900};
const dark:React.CSSProperties={border:0,borderRadius:11,padding:'10px 14px',background:'#111827',color:'#fff',fontWeight:800};
const small:React.CSSProperties={border:0,borderRadius:9,padding:'7px 9px',background:'#f1f5f9',fontWeight:800};
const row:React.CSSProperties={display:'flex',alignItems:'center',gap:10,padding:10,border:'1px solid #eef2f7',borderRadius:14};
const muted:React.CSSProperties={fontSize:13,color:'#64748b',lineHeight:1.5};
const th:React.CSSProperties={padding:12,textAlign:'left',borderBottom:'1px solid #e5e7eb',whiteSpace:'nowrap'};
const td:React.CSSProperties={padding:12,borderBottom:'1px solid #f1f5f9'};
function Card({title,children}:{title:string,children:React.ReactNode}){return <section style={{background:'#fff',border:'1px solid #e5e7eb',borderRadius:20,padding:18,boxShadow:'0 10px 30px #0f172a08'}}><h3 style={{marginTop:0}}>{title}</h3>{children}</section>}
function Stat({label,value}:{label:string,value:any}){return <div style={{padding:12,borderRadius:14,background:'#f8fafc'}}><div style={{fontSize:11,color:'#64748b'}}>{label}</div><b style={{fontSize:20}}>{value}</b></div>}
