import { NextRequest, NextResponse } from 'next/server';
const SB=process.env.SUPABASE_URL||'https://mbsnpcdmenfufhbctoek.supabase.co';
const KEY=process.env.SUPABASE_SERVICE_ROLE_KEY||process.env.SUPABASE_PUBLISHABLE_KEY||'sb_publishable_rwwoH9hpk6cg3woGveNObw_C00pNZsx';
const CREATOR='khoungbell7777';
async function rpc(name:string,body:Record<string,unknown>){const r=await fetch(`${SB}/rest/v1/rpc/${name}`,{method:'POST',headers:{apikey:KEY,Authorization:`Bearer ${KEY}`,'Content-Type':'application/json'},body:JSON.stringify(body),cache:'no-store'});const t=await r.text();let d:any={};try{d=JSON.parse(t)}catch{d={error:t}}if(!r.ok)throw new Error(d?.message||d?.error||`RPC ${r.status}`);return d}
async function roblox(url:string,init?:RequestInit){const r=await fetch(url,{...init,cache:'no-store',headers:{'User-Agent':'RBLXFinder-Plus/2.2',...(init?.headers||{})}});const t=await r.text();let d:any={};try{d=JSON.parse(t)}catch{d={message:t}}if(!r.ok)throw new Error(d?.message||`Roblox ${r.status}`);return d}
export async function POST(req:NextRequest){try{const b=await req.json();const a=String(b?.action||'');
if(a==='creator-login'){const password=String(b.password||'');if(String(b.username||'').trim()!==CREATOR||!password)return NextResponse.json({ok:false,error:'invalid_creator_credentials'},{status:401});const d=await rpc('rblx_creator_login',{p_username:CREATOR,p_password:password});return NextResponse.json(d)}
if(a==='resolve'){const username=String(b.username||'').trim();if(!username)return NextResponse.json({ok:false,error:'missing_username'},{status:400});const d=await roblox('https://users.roblox.com/v1/usernames/users',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({usernames:[username],excludeBannedUsers:false})});const u=d?.data?.[0];if(!u?.id)return NextResponse.json({ok:false,error:'user_not_found'},{status:404});return NextResponse.json({ok:true,user:u})}
if(a==='grant'){const password=String(b.password||'');if(!password)return NextResponse.json({ok:false,error:'creator_auth_required'},{status:401});const username=String(b.username||'').trim();const d=await roblox('https://users.roblox.com/v1/usernames/users',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({usernames:[username],excludeBannedUsers:false})});const u=d?.data?.[0];if(!u?.id)return NextResponse.json({ok:false,error:'user_not_found'},{status:404});const out=await rpc('rblx_creator_grant',{p_username:CREATOR,p_password:password,p_user_id:Number(u.id),p_note:String(b.note||'RBLXFinder Plus').slice(0,300)});return NextResponse.json({...out,user:u})}
if(a==='start-verification'){const id=Number(b.userId);if(!Number.isInteger(id)||id<=0)return NextResponse.json({ok:false,error:'invalid_user_id'},{status:400});return NextResponse.json(await rpc('rblx_plus_start',{p_user_id:id}))}
if(a==='verify'){const id=Number(b.userId),code=String(b.code||'').trim();if(!Number.isInteger(id)||id<=0||!code)return NextResponse.json({ok:false,error:'missing_verification'},{status:400});const p=await roblox(`https://users.roblox.com/v1/users/${id}`);if(!String(p?.description||'').toUpperCase().includes(code.toUpperCase()))return NextResponse.json({ok:false,error:'code_not_in_profile'});return NextResponse.json(await rpc('rblx_plus_verify',{p_user_id:id,p_code:code}))}
if(a==='status'){const id=Number(b.userId);if(!Number.isInteger(id)||id<=0)return NextResponse.json({plus:false},{status:400});return NextResponse.json(await rpc('rblx_plus_status',{p_user_id:id}))}
return NextResponse.json({ok:false,error:'unknown_action'},{status:400});}catch(e){return NextResponse.json({ok:false,error:e instanceof Error?e.message:'creator_api_failed'},{status:500})}}
