import { NextRequest,NextResponse } from 'next/server';
const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Methods':'GET, POST, OPTIONS','Access-Control-Allow-Headers':'Content-Type, Authorization'};
export async function OPTIONS(){return new NextResponse(null,{status:204,headers:cors})}
const out=(d:any,status=200)=>NextResponse.json(d,{status,headers:cors});
const SB=process.env.SUPABASE_URL||'https://mbsnpcdmenfufhbctoek.supabase.co';
const KEY=process.env.SUPABASE_SERVICE_ROLE_KEY||process.env.SUPABASE_PUBLISHABLE_KEY||'';const CREATOR='khoungbell7777';
async function rpc(name:string,body:Record<string,unknown>){const r=await fetch(`${SB}/rest/v1/rpc/${name}`,{method:'POST',headers:{apikey:KEY,Authorization:`Bearer ${KEY}`,'Content-Type':'application/json'},body:JSON.stringify(body),cache:'no-store'});const t=await r.text();let d:any={};try{d=JSON.parse(t)}catch{d={error:t}}if(!r.ok)throw new Error(d?.message||d?.error||`RPC ${r.status}`);return d}
async function roblox(url:string,init?:RequestInit){const r=await fetch(url,{...init,cache:'no-store',headers:{'User-Agent':'RBLXFinder-Plus/3.0',...(init?.headers||{})}});const t=await r.text();let d:any={};try{d=JSON.parse(t)}catch{d={message:t}}if(!r.ok)throw new Error(d?.message||`Roblox ${r.status}`);return d}
export async function GET(req:NextRequest){try{const u=new URL(req.url);if(u.searchParams.get('action')==='leaderboard')return out({ok:true,leaderboard:await rpc('rblx_creator_leaderboard',{p_limit:50})});return out({ok:false,error:'unknown_action'},400)}catch(e){return out({ok:false,error:e instanceof Error?e.message:'creator_api_failed'},500)}}
export async function POST(req:NextRequest){try{const b=await req.json(),a=String(b?.action||'');
if(a==='creator-login'){const password=String(b.password||'');if(String(b.username||'').trim()!==CREATOR||!password)return out({ok:false,error:'invalid_creator_credentials'},401);return out(await rpc('rblx_creator_login',{p_username:CREATOR,p_password:password}))}
if(a==='resolve'){const username=String(b.username||'').trim();if(!username)return out({ok:false,error:'missing_username'},400);const d=await roblox('https://users.roblox.com/v1/usernames/users',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({usernames:[username],excludeBannedUsers:false})});const u=d?.data?.[0];if(!u?.id)return out({ok:false,error:'user_not_found'},404);return out({ok:true,user:u})}
if(a==='record-donation'){const password=String(b.password||''),id=Number(b.userId),username=String(b.username||'').trim(),amount=Number(b.amount);if(!password||!Number.isInteger(id)||id<=0||!username||!Number.isInteger(amount)||amount<=0)return out({ok:false,error:'invalid_donation'},400);return out(await rpc('rblx_creator_record_donation',{p_username:CREATOR,p_password:password,p_user_id:id,p_roblox_username:username,p_amount:amount,p_note:String(b.note||'').slice(0,300)}))}
if(a==='grant'){const password=String(b.password||'');if(!password)return out({ok:false,error:'creator_auth_required'},401);const username=String(b.username||'').trim();const d=await roblox('https://users.roblox.com/v1/usernames/users',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({usernames:[username],excludeBannedUsers:false})});const u=d?.data?.[0];if(!u?.id)return out({ok:false,error:'user_not_found'},404);const result=await rpc('rblx_creator_grant',{p_username:CREATOR,p_password:password,p_user_id:Number(u.id),p_note:String(b.note||'RBLXFinder Plus').slice(0,300)});return out({...result,user:u})}
if(a==='status'){const id=Number(b.userId);if(!Number.isInteger(id)||id<=0)return out({plus:false},400);return out(await rpc('rblx_plus_status',{p_user_id:id}))}
return out({ok:false,error:'unknown_action'},400)}catch(e){return out({ok:false,error:e instanceof Error?e.message:'creator_api_failed'},500)}}
