'use client';
import {useEffect,useMemo,useState} from 'react';
const rbx=(action:string,body:any)=>fetch('/api/roblox',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,...body})}).then(r=>r.json());
const key='rblxfinder_plus_favorites';
export default function RobloxPlus(){
 const [q,setQ]=useState('');const [servers,setServers]=useState<any[]>([]);const [game,setGame]=useState<any>(null);const [busy,setBusy]=useState(false);const [filter,setFilter]=useState(3);const [auto,setAuto]=useState(false);const [favorites,setFavorites]=useState<string[]>([]);const [msg,setMsg]=useState('');
 useEffect(()=>{try{setFavorites(JSON.parse(localStorage.getItem(key)||'[]'))}catch{}},[]);
 useEffect(()=>{if(!auto||!game?.universeId)return;const t=setInterval(()=>loadServers(game.universeId),15000);return()=>clearInterval(t)},[auto,game]);
 const notify=(x:string)=>{setMsg(x);setTimeout(()=>setMsg(''),2600)};
 async function loadServers(id:number){setBusy(true);try{const d=await rbx('servers',{universeId:id});const rows=(d.data||[]).filter((x:any)=>(x.playing||0)<=filter).sort((a:any,b:any)=>(a.playing||0)-(b.playing||0));setServers(rows)}catch{notify('Không tải được server')}finally{setBusy(false)}}
 async function search(){if(!q.trim())return;setBusy(true);try{const d=await rbx('games',{q});const g=(d.games||[])[0];if(!g)return notify('Không tìm thấy game');setGame(g);loadServers(g.universeId||g.id)}finally{setBusy(false)}}
 const toggle=(id:string)=>{const n=favorites.includes(id)?favorites.filter(x=>x!==id):[...favorites,id];setFavorites(n);localStorage.setItem(key,JSON.stringify(n));notify(favorites.includes(id)?'Đã bỏ yêu thích':'Đã lưu yêu thích')};
 const top=useMemo(()=>servers.slice(0,10),[servers]);
 const css=`body{margin:0;background:#f6f7fb;color:#171827;font-family:Inter,system-ui,sans-serif}.wrap{max-width:1180px;margin:auto;padding:20px}.hero{background:linear-gradient(135deg,#5545d8,#9c75ff);color:white;border-radius:28px;padding:28px}.hero h1{font-size:42px;margin:8px 0}.card{background:#fff;border:1px solid #e4e5ed;border-radius:20px;padding:18px;margin-top:15px;box-shadow:0 12px 40px #1718270c}.row{display:flex;gap:9px;flex-wrap:wrap}.input{flex:1;min-width:200px;padding:13px;border:1px solid #ddddea;border-radius:12px;font:inherit}.btn{border:0;border-radius:12px;padding:12px 16px;font-weight:900;cursor:pointer}.primary{background:#6555dd;color:#fff}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:12px}.server{display:grid;grid-template-columns:90px 1fr auto;gap:10px;align-items:center;padding:12px 0;border-bottom:1px solid #eee}.pill{background:#f0eeff;color:#5f50d5;padding:6px 9px;border-radius:999px;font-weight:800;font-size:12px}.thumb{width:100%;aspect-ratio:16/9;object-fit:cover;border-radius:16px;background:#eee}.muted{color:#74788b}.switch{display:flex;gap:8px;align-items:center}@media(max-width:650px){.wrap{padding:12px}.hero h1{font-size:32px}.server{grid-template-columns:1fr}.server .btn{width:100%}}`;
 return <main><style>{css}</style><div className="wrap"><a href="/roblox" className="muted">← RBLXFinder Roblox</a><section className="hero"><div className="pill">ROBLOX PLUS POWER CENTER</div><h1>Server Power & Game Intelligence</h1><p>Plus chỉ dành cho Roblox. Free Fire không có Plus.</p><div className="row"><input className="input" value={q} onChange={e=>setQ(e.target.value)} placeholder="Tên game Roblox"/><button className="btn primary" onClick={search} disabled={busy}>{busy?'Đang tải...':'Tìm game'}</button></div></section>{game&&<section className="card"><div className="grid"><div><img className="thumb" src={game.thumbnailUrl||'/free-fire-thumb.svg'} onError={e=>(e.currentTarget.style.visibility='hidden')}/></div><div><h2>{game.name}</h2><p className="muted">Universe ID: {game.universeId||game.id}</p><p>{game.description||'Game Roblox'}</p><button className="btn primary" onClick={()=>loadServers(game.universeId||game.id)}>Làm mới server</button> <button className="btn" onClick={()=>toggle(String(game.universeId||game.id))}>{favorites.includes(String(game.universeId||game.id))?'★ Đã lưu':'☆ Lưu game'}</button></div></div></section>}
 <section className="card"><h2>⚡ Bộ lọc server nâng cao</h2><div className="row"><button className="btn" onClick={()=>setFilter(1)}>0–1 người</button><button className="btn" onClick={()=>setFilter(3)}>0–3 người</button><button className="btn" onClick={()=>setFilter(5)}>0–5 người</button><button className="btn" onClick={()=>setFilter(20)}>0–20 người</button><label className="switch">Tự refresh <input type="checkbox" checked={auto} onChange={e=>setAuto(e.target.checked)}/></label></div><p className="muted">Đang lọc ≤ {filter} người · {servers.length} server phù hợp{auto?' · tự cập nhật mỗi 15 giây':''}</p>{top.map((s:any)=><div className="server" key={s.id}><b>{s.playing||0}/{s.maxPlayers||0}</b><code>{s.id}</code><button className="btn" onClick={()=>navigator.clipboard?.writeText(s.id).then(()=>notify('Đã copy server ID'))}>Copy ID</button></div>)}</section>
 <div className="grid"><section className="card"><h3>📌 Server Watcher</h3><p className="muted">Theo dõi game và tự làm mới danh sách server để tìm server ít người nhanh hơn.</p></section><section className="card"><h3>★ Favorites</h3><p className="muted">Game đã lưu: {favorites.length}. Dữ liệu được lưu trên thiết bị của bạn.</p></section><section className="card"><h3>📊 Game Intelligence</h3><p className="muted">Thumbnail, player count, visits, creator và thông tin game nâng cao sẽ được mở rộng tiếp.</p></section></div></div>{msg&&<div style={{position:'fixed',bottom:20,left:'50%',transform:'translateX(-50%)',background:'#171827',color:'#fff',padding:'12px 18px',borderRadius:999,fontWeight:800}}>{msg}</div>}</main>
}